version: '3.7'

services:
  testdb:
    image: postgres
    ports:
        - "8050:5432"
    container_name: mystoreaid_test_db
    environment:
        POSTGRES_PASSWORD: testerpass
        POSTGRES_USER: tester
        POSTGRES_DB: mystoreaid_test
        PGDATA: /data/postgres
      
